// <auto-generated />
using System;
using AppEscolar_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppEscolar_BackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AdmModel", b =>
                {
                    b.Property<Guid>("Usuario_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Usuario_id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AlunoModel", b =>
                {
                    b.Property<Guid>("Usuario_Id")
                        .HasColumnType("uuid");

                    b.Property<float>("Creditos")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Ra")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Usuario_Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.HistoricoDoacoesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlunoIdUso")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FoiUsado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ValorReais")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoIdUso");

                    b.ToTable("HistoricoDoacoes");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.NoticiasModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoNoticia")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.UsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AdmModel", b =>
                {
                    b.HasOne("AppEscolar_BackEnd.Model.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AlunoModel", b =>
                {
                    b.HasOne("AppEscolar_BackEnd.Model.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.HistoricoDoacoesModel", b =>
                {
                    b.HasOne("AppEscolar_BackEnd.Model.AlunoModel", "AlunoQueUsou")
                        .WithMany("HistoricoDoacoes")
                        .HasForeignKey("AlunoIdUso");

                    b.Navigation("AlunoQueUsou");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.NoticiasModel", b =>
                {
                    b.HasOne("AppEscolar_BackEnd.Model.AdmModel", "AutorAdm")
                        .WithMany("NoticiasPublicadas")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorAdm");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AdmModel", b =>
                {
                    b.Navigation("NoticiasPublicadas");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AlunoModel", b =>
                {
                    b.Navigation("HistoricoDoacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
