// <auto-generated />
using System;
using AppEscolar_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppEscolar_BackEnd.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AdmModel", b =>
                {
                    b.Property<int>("Usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Usuario_id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Usuario_id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AlunoModel", b =>
                {
                    b.Property<int>("Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Usuario_Id"));

                    b.Property<float>("Creditos")
                        .HasColumnType("real");

                    b.Property<float>("Int")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Ra")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Usuario_Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.HistoricoDoacoesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoModelUsuario_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Aluno_Id")
                        .HasColumnType("integer");

                    b.Property<decimal>("Creditos_Ganhos")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Data_Doacao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlunoModelUsuario_Id");

                    b.ToTable("HistoricoDoacoes");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.NoticiasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdmModelUsuario_id")
                        .HasColumnType("integer");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoNoticia")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdmModelUsuario_id");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.HistoricoDoacoesModel", b =>
                {
                    b.HasOne("AppEscolar_BackEnd.Model.AlunoModel", null)
                        .WithMany("HistoricoDoacoes")
                        .HasForeignKey("AlunoModelUsuario_Id");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.NoticiasModel", b =>
                {
                    b.HasOne("AppEscolar_BackEnd.Model.AdmModel", null)
                        .WithMany("NoticiasPublicadas")
                        .HasForeignKey("AdmModelUsuario_id");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AdmModel", b =>
                {
                    b.Navigation("NoticiasPublicadas");
                });

            modelBuilder.Entity("AppEscolar_BackEnd.Model.AlunoModel", b =>
                {
                    b.Navigation("HistoricoDoacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
